name: Reentrenar modelo

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python retrain.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add iris_model.joblib
          git commit -m "Modelo actualizado automáticamente"
          git push || echo "Sin cambios"
